# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b919390bfca90221032fd181eb3f3d81908189cdb2d4368296632885d8cca44f18180e670c834a8398f80a903507984d52865f9016005fa833950b72df684c0e

test:
  secret_key_base: 272632cc9a0e413bf5ab6b03fa23f301a802885877dc77f81cf066fd282acaeef21b3eb62962577bc02ce36dfd2e540f76e3f0c31d8b8cbcfd8765dd643f5a7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
